services:

  mysql:
    image: mysql:8.0
    container_name: guac-mysql

    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole

    restart: unless-stopped

    depends_on:
      - mysql

    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      GUACD_HOSTNAME: ${GUACD_HOST}
      GUACD_PORT: 4822

      MYSQL_HOSTNAME: mysql
      MYSQL_PORT: 3306

      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  mysql_data:
